# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 430)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/windows/Text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("\n"
"QLabel#Background{\n"
"    border-radius:10px;\n"
"    background-color:#363B40;\n"
"}\n"
"/* 向在移动 */\n"
"QTabWidget::tab-bar {\n"
"    left:20px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                    stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                   stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border:2px solid #C4C4C3;\n"
"    border-bottom-color:red;\n"
"    border-top-left-radius:4px;\n"
"    border-top-right-radius:4px;\n"
"    min-width:8px;\n"
"    padding:2px;\n"
"}\n"
"\n"
"/* 标签被选中时或鼠标悬浮时 */\n"
"QTabBar::tab:selected,QTabBar::tab:hover {\n"
"    background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"/* 标签被选中时 */\n"
"QTabBar::tab:selected {\n"
"    border-color:#9B9B9B;\n"
"    border-bottom-color:#C2C7CB;\n"
"}\n"
"\n"
"/* 标签未被选中时 */\n"
"QTabBar::tab:!selected {\n"
"    margin-top:2px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font: 25 9pt \"Microsoft YaHei\";\n"
"    /* 边框 */\n"
"    border: 2px solid red;\n"
"\n"
"    /* 倒角 */\n"
"    border-radius: 5px;\n"
"\n"
"    /* 就像墙上挂着的两个相框,margin指的是相框与相框的距离\n"
"       padding指的是每个相框里照片与相框边框的距离 */\n"
"    margin-top: 20px;\n"
"\n"
"}\n"
"QGroupBox::title {\n"
"    color:#fff;\n"
"    /* 位置 */    \n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"\n"
"    /* 内边框,上下和左右 */\n"
"    padding: 10px 15px;\n"
"}\n"
"QLineEdit:hover{\n"
"       background-color:transparent;\n"
"    border-radius:7px;\n"
"    border:none;\n"
"    border-bottom:2px solid rgb(11, 1, 127);\n"
"    color:rgb(0, 0, 0);\n"
"    padding-bottom:7px;\n"
"}\n"
"QLineEdit{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    border-radius:7px;\n"
"    color:rgb(0,0,0);\n"
"    border-bottom:2px solid rgb(11, 1, 127);\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"border:1px solid transparent;\n"
"height:10;\n"
"text-align:right;\n"
"border-radius:6px;\n"
"background-color: rgb(63, 63, 63);\n"
"}\n"
" \n"
"//滑块\n"
"QProgressBar::chunk{\n"
"border-radius:6px;\n"
"border:1px solid #1976D3;\n"
"background-color:#1976D3;\n"
"}")
        self.Background = QtWidgets.QLabel(Form)
        self.Background.setGeometry(QtCore.QRect(0, 0, 800, 430))
        self.Background.setStyleSheet("")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Tools = QtWidgets.QTabWidget(Form)
        self.Tools.setGeometry(QtCore.QRect(2, 20, 800, 391))
        self.Tools.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-color: rgb(255, 255, 255);")
        self.Tools.setTabBarAutoHide(True)
        self.Tools.setObjectName("Tools")
        self.English_recite = QtWidgets.QWidget()
        self.English_recite.setObjectName("English_recite")
        self.Custom_words = QtWidgets.QLineEdit(self.English_recite)
        self.Custom_words.setGeometry(QtCore.QRect(90, 330, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.Custom_words.setFont(font)
        self.Custom_words.setStyleSheet("")
        self.Custom_words.setText("")
        self.Custom_words.setObjectName("Custom_words")
        self.label = QtWidgets.QLabel(self.English_recite)
        self.label.setGeometry(QtCore.QRect(10, 337, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff;")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.English_recite)
        self.line.setGeometry(QtCore.QRect(0, 321, 795, 3))
        self.line.setStyleSheet("background-color: rgb(3, 23, 26);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.english_words = QtWidgets.QLabel(self.English_recite)
        self.english_words.setGeometry(QtCore.QRect(0, 0, 421, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.english_words.sizePolicy().hasHeightForWidth())
        self.english_words.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(36)
        self.english_words.setFont(font)
        self.english_words.setText("")
        self.english_words.setObjectName("english_words")
        self.line_2 = QtWidgets.QFrame(self.English_recite)
        self.line_2.setGeometry(QtCore.QRect(0, 80, 800, 17))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.English_recite)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 90, 791, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.copy = QtWidgets.QToolButton(self.groupBox_2)
        self.copy.setGeometry(QtCore.QRect(0, 0, 21, 20))
        self.copy.setStyleSheet("background-color:transparent;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/control/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy.setIcon(icon1)
        self.copy.setObjectName("copy")
        self.Details = QtWidgets.QPushButton(self.groupBox_2)
        self.Details.setGeometry(QtCore.QRect(670, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(11)
        self.Details.setFont(font)
        self.Details.setStyleSheet("background-color: rgb(3, 167, 200);\n"
"border-radius:8px;\n"
"\n"
"")
        self.Details.setObjectName("Details")
        self.youdao = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.youdao.setGeometry(QtCore.QRect(670, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.youdao.setFont(font)
        self.youdao.setObjectName("youdao")
        self.love_english = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.love_english.setGeometry(QtCore.QRect(670, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.love_english.setFont(font)
        self.love_english.setObjectName("love_english")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setGeometry(QtCore.QRect(0, 30, 671, 181))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 R")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color:transparent;\n"
"border:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.start_Custom = QtWidgets.QPushButton(self.English_recite)
        self.start_Custom.setGeometry(QtCore.QRect(690, 330, 93, 28))
        self.start_Custom.setObjectName("start_Custom")
        self.next = QtWidgets.QToolButton(self.English_recite)
        self.next.setGeometry(QtCore.QRect(700, 9, 40, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.next.setFont(font)
        self.next.setStyleSheet("background-color:transparent;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/English_tools/English_tools/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon2)
        self.next.setIconSize(QtCore.QSize(26, 26))
        self.next.setObjectName("next")
        self.next_ = QtWidgets.QToolButton(self.English_recite)
        self.next_.setGeometry(QtCore.QRect(657, 12, 51, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(11)
        self.next_.setFont(font)
        self.next_.setStyleSheet("background-color:transparent;\n"
"color:#fff")
        self.next_.setObjectName("next_")
        self.last_ = QtWidgets.QToolButton(self.English_recite)
        self.last_.setGeometry(QtCore.QRect(689, 53, 51, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(11)
        self.last_.setFont(font)
        self.last_.setStyleSheet("background-color:transparent;\n"
"color:#fff")
        self.last_.setObjectName("last_")
        self.last = QtWidgets.QToolButton(self.English_recite)
        self.last.setGeometry(QtCore.QRect(657, 50, 40, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.last.setFont(font)
        self.last.setStyleSheet("background-color:transparent;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/English_tools/English_tools/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.last.setIcon(icon3)
        self.last.setIconSize(QtCore.QSize(26, 26))
        self.last.setObjectName("last")
        self.sound = QtWidgets.QToolButton(self.English_recite)
        self.sound.setGeometry(QtCore.QRect(740, 20, 51, 51))
        self.sound.setStyleSheet("background: transparent;   ")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/English_tools/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound.setIcon(icon4)
        self.sound.setIconSize(QtCore.QSize(49, 49))
        self.sound.setObjectName("sound")
        self.Tools.addTab(self.English_recite, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.en_text = QtWidgets.QLineEdit(self.tab)
        self.en_text.setGeometry(QtCore.QRect(210, 47, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.en_text.setFont(font)
        self.en_text.setStyleSheet("")
        self.en_text.setObjectName("en_text")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 51, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#fff;")
        self.label_2.setObjectName("label_2")
        self.file_search_en = QtWidgets.QToolButton(self.tab)
        self.file_search_en.setGeometry(QtCore.QRect(750, 51, 31, 31))
        self.file_search_en.setStyleSheet("background-color:transparent;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/control/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_search_en.setIcon(icon5)
        self.file_search_en.setObjectName("file_search_en")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 94, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#fff;")
        self.label_4.setObjectName("label_4")
        self.dn_text = QtWidgets.QLineEdit(self.tab)
        self.dn_text.setGeometry(QtCore.QRect(210, 86, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dn_text.setFont(font)
        self.dn_text.setStyleSheet("")
        self.dn_text.setObjectName("dn_text")
        self.file_search_dn = QtWidgets.QToolButton(self.tab)
        self.file_search_dn.setGeometry(QtCore.QRect(750, 91, 31, 31))
        self.file_search_dn.setStyleSheet("background-color:transparent;")
        self.file_search_dn.setIcon(icon5)
        self.file_search_dn.setObjectName("file_search_dn")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 159, 791, 204))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.groupBox.setObjectName("groupBox")
        self.finish_text = QtWidgets.QTextBrowser(self.groupBox)
        self.finish_text.setGeometry(QtCore.QRect(0, 37, 791, 168))
        self.finish_text.setStyleSheet("background-color:transparent;\n"
"border:none;")
        self.finish_text.setObjectName("finish_text")
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(0, 0, 21, 20))
        self.toolButton.setStyleSheet("background-color:transparent;")
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 120, 181, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Over_write_file = QtWidgets.QCheckBox(self.layoutWidget)
        self.Over_write_file.setStyleSheet("background-color:transparent;")
        self.Over_write_file.setObjectName("Over_write_file")
        self.horizontalLayout.addWidget(self.Over_write_file)
        self.write_log = QtWidgets.QCheckBox(self.layoutWidget)
        self.write_log.setStyleSheet("background-color:transparent;")
        self.write_log.setObjectName("write_log")
        self.horizontalLayout.addWidget(self.write_log)
        self.start = QtWidgets.QPushButton(self.tab)
        self.start.setGeometry(QtCore.QRect(210, 120, 121, 31))
        self.start.setStyleSheet("color:#fff;\n"
"background-color: rgb(29, 140, 225);\n"
"border-radius: 10px; \n"
"")
        self.start.setObjectName("start")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(-1, 155, 799, 2))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(0, 34, 800, 9))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(330, -1, 151, 40))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent;")
        self.label_5.setObjectName("label_5")
        self.line_3.raise_()
        self.en_text.raise_()
        self.label_2.raise_()
        self.file_search_en.raise_()
        self.label_4.raise_()
        self.dn_text.raise_()
        self.file_search_dn.raise_()
        self.groupBox.raise_()
        self.layoutWidget.raise_()
        self.start.raise_()
        self.line_4.raise_()
        self.label_5.raise_()
        self.Tools.addTab(self.tab, "")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(700, 0, 91, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.WindowsTitle = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.WindowsTitle.setContentsMargins(0, 0, 0, 0)
        self.WindowsTitle.setObjectName("WindowsTitle")
        self.small = QtWidgets.QPushButton(self.layoutWidget1)
        self.small.setMinimumSize(QtCore.QSize(24, 24))
        self.small.setMaximumSize(QtCore.QSize(24, 24))
        self.small.setStyleSheet("border-radius:12;\n"
"background-color: yellow;")
        self.small.setText("")
        self.small.setObjectName("small")
        self.WindowsTitle.addWidget(self.small)
        self.Max = QtWidgets.QPushButton(self.layoutWidget1)
        self.Max.setMinimumSize(QtCore.QSize(24, 24))
        self.Max.setMaximumSize(QtCore.QSize(24, 24))
        self.Max.setStyleSheet("border-radius:12;\n"
"background-color: green;")
        self.Max.setText("")
        self.Max.setObjectName("Max")
        self.WindowsTitle.addWidget(self.Max)
        self.exit = QtWidgets.QPushButton(self.layoutWidget1)
        self.exit.setMinimumSize(QtCore.QSize(24, 24))
        self.exit.setMaximumSize(QtCore.QSize(24, 24))
        self.exit.setStyleSheet("border-radius:12;\n"
"background-color: red;")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.WindowsTitle.addWidget(self.exit)
        self.set = QtWidgets.QPushButton(Form)
        self.set.setGeometry(QtCore.QRect(642, 0, 51, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.set.setFont(font)
        self.set.setStyleSheet("background-color: rgb(192, 192, 192);\n"
"border-radius: 10px; \n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.set.setObjectName("set")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(170, 10, 461, 20))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        self.Tools.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "输入英语"))
        self.groupBox_2.setTitle(_translate("Form", "单词信息"))
        self.copy.setText(_translate("Form", "..."))
        self.copy.setShortcut(_translate("Form", "Ctrl+C"))
        self.Details.setText(_translate("Form", "详细信息"))
        self.youdao.setText(_translate("Form", "有道"))
        self.love_english.setText(_translate("Form", "爱词霸"))
        self.start_Custom.setText(_translate("Form", "获取"))
        self.next.setText(_translate("Form", "..."))
        self.next_.setText(_translate("Form", "Next"))
        self.last_.setText(_translate("Form", "Last"))
        self.last.setText(_translate("Form", "..."))
        self.sound.setText(_translate("Form", "..."))
        self.Tools.setTabText(self.Tools.indexOf(self.English_recite), _translate("Form", "英语学习"))
        self.label_2.setText(_translate("Form", "加密 /文件/文本/目录:"))
        self.file_search_en.setText(_translate("Form", "..."))
        self.label_4.setText(_translate("Form", "解密 /文件/文本/目录:"))
        self.file_search_dn.setText(_translate("Form", "..."))
        self.groupBox.setTitle(_translate("Form", "文本浏览"))
        self.toolButton.setText(_translate("Form", "..."))
        self.toolButton.setShortcut(_translate("Form", "Ctrl+C"))
        self.Over_write_file.setText(_translate("Form", "覆盖文件"))
        self.write_log.setText(_translate("Form", "写入日志"))
        self.start.setText(_translate("Form", "Start"))
        self.start.setShortcut(_translate("Form", "Return"))
        self.label_5.setText(_translate("Form", "Encrypt"))
        self.Tools.setTabText(self.Tools.indexOf(self.tab), _translate("Form", "加密系统"))
        self.exit.setShortcut(_translate("Form", "Esc"))
        self.set.setText(_translate("Form", "设置"))
import res_rc
