# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 148)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/windows/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.fontComboBox = QtWidgets.QFontComboBox(Dialog)
        self.fontComboBox.setGeometry(QtCore.QRect(60, 54, 279, 22))
        self.fontComboBox.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:#fff")
        self.fontComboBox.setObjectName("fontComboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#fff")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(60, 94, 87, 22))
        self.comboBox.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:#fff")
        self.comboBox.setObjectName("comboBox")
        self.Background = QtWidgets.QLabel(Dialog)
        self.Background.setGeometry(QtCore.QRect(0, 0, 800, 430))
        self.Background.setStyleSheet("background-color: #363b40;\n"
"border-radius: 10px; \n"
"")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 10, 91, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.WindowsTitle = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.WindowsTitle.setContentsMargins(0, 0, 0, 0)
        self.WindowsTitle.setObjectName("WindowsTitle")
        self.small = QtWidgets.QPushButton(self.layoutWidget)
        self.small.setMinimumSize(QtCore.QSize(24, 24))
        self.small.setMaximumSize(QtCore.QSize(24, 24))
        self.small.setStyleSheet("border-radius:12;\n"
"background-color: yellow;")
        self.small.setText("")
        self.small.setObjectName("small")
        self.WindowsTitle.addWidget(self.small)
        self.Max = QtWidgets.QPushButton(self.layoutWidget)
        self.Max.setMinimumSize(QtCore.QSize(24, 24))
        self.Max.setMaximumSize(QtCore.QSize(24, 24))
        self.Max.setStyleSheet("border-radius:12;\n"
"background-color: green;")
        self.Max.setText("")
        self.Max.setObjectName("Max")
        self.WindowsTitle.addWidget(self.Max)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setMinimumSize(QtCore.QSize(24, 24))
        self.exit.setMaximumSize(QtCore.QSize(24, 24))
        self.exit.setStyleSheet("border-radius:12;\n"
"background-color: red;")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.WindowsTitle.addWidget(self.exit)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#fff")
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 38, 10, 81))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Background.raise_()
        self.fontComboBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.comboBox.raise_()
        self.layoutWidget.raise_()
        self.label_3.raise_()
        self.line.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "字体"))
        self.label_2.setText(_translate("Dialog", "大小"))
        self.label_3.setText(_translate("Dialog", "字体设置"))
import res_rc
